version: "3"
services:
  maria_app:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - wisata_network
  go_app:
    build: .
    depends_on:
      - maria_app
    ports: 
      - "3000:3000"
    networks:
      - wisata_network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - wisata_network

networks:
  wisata_network: